### ISSUE TITLE
Model training approach (tuners)

### ISSUE THREAD

**Issue by Marko-Shevchuk** [PNU-SE-AIteam/cifar-10-stable-diffusion-detection#25]
- Find whether Hyperband can be ran cumulatively across multiple trainings (so that we don't run into the 12 hour limit). 
- Find whether BayesianOptimizer can be ran cumulatively (so that we can just increase the training parameters and it will continue to train)
- If it can't be ran separably, find out how to calculate BayesianOptimizer approximate train time / approximate epoch amount.
- **If it is possible, train using BayesianOptimizer.**
(This applies to Hyperband as well, but I couldn't get it to run separably or continuously.)

**Comment by maidennnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn** [comment]
Hyperband is cumulative if interrupted in interactive session.
