### ISSUE TITLE
MBConv1 flawed expansion

### ISSUE THREAD

**Issue by Marko-Shevchuk** [PNU-SE-AIteam/cifar-10-stable-diffusion-detection#30]
Shouldn't the line 
`x = layers.Conv2D(expansion, (1,   1), padding='same', use_bias=False)(input_tensor)`
Be like 
`x = layers.Conv2D(expansion * input_tensor.shape[-1], (1,   1), padding='same', use_bias=False)(input_tensor)`

**Comment by maidennnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn** [comment]
I think it definitely should be like that🤔

**Comment by Marko-Shevchuk** [comment]
Expansion factor is supposed to denote the increase of the input, so I'd guess it's good practice to multiply by the input shape, moreover expansion factor is already hyperparametrised.

**Comment by sgorrister** [comment]
I fixed💪
